const $=id=>document.getElementById(id);const CFG='bearcrest_v93_config';let config=JSON.parse(localStorage.getItem(CFG)||'{"webAppUrl":""}');let loans=[],lenders=[];const fields=['recordId','loanNumber','dateReceived','borrowerName','entityName','phone','email','program','propertyAddress','loanAmount','purchasePrice','rehabBudget','arv','status','lender','nextFollowUp','targetClosing','missingDocs','notes'];const statuses=['New Lead','Reviewing','Submitted','Approved','Closing','Closed','Dead'];const today=()=>new Date().toISOString().slice(0,10);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=v=>v?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(v)):'';
function setConnection(t,good=false){$('syncStatus').textContent=t;$('connectionDot').style.background=good?'#65d38e':'#d96b6b'}
async function api(action,payload={}){if(!config.webAppUrl)throw new Error('Add your Apps Script Web App URL in Settings.');const r=await fetch(config.webAppUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload})});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j.data}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name+'View'));document.querySelectorAll('.nav').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$('pageTitle').textContent=name[0].toUpperCase()+name.slice(1);if(name==='calendar')renderCalendar();if(name==='communications')renderComms()}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('collapseBtn').onclick=()=>$('sidebar').classList.toggle('collapsed');
async function loadAll(){try{setConnection('Syncing…');const d=await api('getAll');loans=d.loans||[];lenders=d.lenders||[];renderAll();setConnection('Google connected',true)}catch(e){setConnection('Connection needed');renderAll();console.warn(e)}}
function renderAll(){renderStats();renderHome();renderLoans();renderPipeline();renderContacts();renderLenders();renderComms()}
function renderStats(){const active=loans.filter(l=>!['Closed','Dead'].includes(l.status)).length,due=loans.filter(l=>l.nextFollowUp&&l.nextFollowUp<=today()&&!['Closed','Dead'].includes(l.status)).length,closing=loans.filter(l=>l.status==='Closing').length,approved=loans.filter(l=>l.status==='Approved').length,closed=loans.filter(l=>l.status==='Closed').length,vol=loans.reduce((a,l)=>a+Number(l.loanAmount||0),0);$('stats').innerHTML=[[active,'Active Loans'],[due,'Follow-ups Due'],[approved,'Approved'],[closing,'Closing'],[closed,'Closed'],[money(vol),'Pipeline Volume']].map(x=>`<div class="stat"><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}
const item=l=>`<div class="listitem"><div><strong>${esc(l.borrowerName||l.loanNumber)}</strong><small>${esc(l.propertyAddress||l.program||'')}</small></div><button onclick="openLoan('${esc(l.recordId)}')">Open</button></div>`;
function renderHome(){$('todayList').innerHTML=loans.filter(l=>l.nextFollowUp&&l.nextFollowUp<=today()&&!['Closed','Dead'].includes(l.status)).slice(0,6).map(item).join('')||'<p>Nothing due today.</p>';$('recentList').innerHTML=[...loans].sort((a,b)=>(b.dateReceived||'').localeCompare(a.dateReceived||'')).slice(0,6).map(item).join('')||'<p>No loans yet.</p>'}
function filtered(){const q=$('loanSearch').value.toLowerCase(),s=$('loanStatus').value;return loans.filter(l=>(!s||l.status===s)&&(!q||Object.values(l).join(' ').toLowerCase().includes(q)))}
function renderLoans(){$('loanRows').innerHTML=filtered().map(l=>`<tr><td>${esc(l.loanNumber)}</td><td><strong>${esc(l.borrowerName)}</strong></td><td>${esc(l.program)}</td><td>${esc(l.propertyAddress)}</td><td><span class="badge">${esc(l.status)}</span></td><td>${money(l.loanAmount)}</td><td>${esc(l.lender)}</td><td>${esc(l.nextFollowUp)}</td><td><button onclick="openLoan('${esc(l.recordId)}')">Open</button></td></tr>`).join('')||'<tr><td colspan="9">No matching loans.</td></tr>'}
function renderPipeline(){$('pipelineBoard').innerHTML=statuses.map(s=>`<section class="pipeline-col"><h3>${s} <small>(${loans.filter(l=>l.status===s).length})</small></h3>${loans.filter(l=>l.status===s).map(l=>`<article class="pipeline-card"><strong>${esc(l.borrowerName||l.loanNumber)}</strong><p>${esc(l.propertyAddress||l.program)}</p><p>${money(l.loanAmount)}</p><button onclick="openLoan('${esc(l.recordId)}')">Open</button></article>`).join('')}</section>`).join('')}
function renderContacts(){const unique=new Map();loans.forEach(l=>{if(l.borrowerName&&!unique.has(l.email||l.phone||l.borrowerName))unique.set(l.email||l.phone||l.borrowerName,l)});$('contactList').innerHTML=[...unique.values()].map(l=>`<article class="contact-card"><h3>${esc(l.borrowerName)}</h3><p>${esc(l.entityName||'')}</p><p>${esc(l.phone||'')}<br>${esc(l.email||'')}</p><button onclick="composeFor('${esc(l.recordId)}')">Email</button></article>`).join('')}
function renderLenders(){const sel=$('lender');const cur=sel.value;const names=[...new Set((lenders||[]).map(x=>typeof x==='string'?x:x.name).filter(Boolean))].sort();sel.innerHTML='<option value="">Select lender</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');if(names.includes(cur))sel.value=cur}
window.openLoan=async id=>{const l=loans.find(x=>x.recordId===id);if(!l)return;fields.forEach(f=>$(f).value=l[f]||'');$('dialogTitle').textContent=l.loanNumber||'Loan';$('deleteBtn').style.visibility='visible';$('loanDialog').showModal()};
async function openNew(){$('loanForm').reset();fields.forEach(f=>{if($(f))$(f).value=''});$('dateReceived').value=today();$('status').value='New Lead';try{$('loanNumber').value=await api('getNextLoanNumber')}catch{$('loanNumber').value='BCF-'+Date.now().toString().slice(-6)}$('dialogTitle').textContent='New Loan';$('deleteBtn').style.visibility='hidden';$('loanDialog').showModal()}
$('newLoanBtn').onclick=openNew;$('closeDialog').onclick=$('cancelBtn').onclick=()=>$('loanDialog').close();$('loanForm').onsubmit=async e=>{e.preventDefault();const btn=$('saveLoanBtn');btn.disabled=true;btn.textContent='Saving…';try{const loan={};fields.forEach(f=>loan[f]=$(f).value);await api('saveLoan',{loan});$('loanDialog').close();await loadAll()}catch(err){alert(err.message)}finally{btn.disabled=false;btn.textContent='Save Loan'}};$('deleteBtn').onclick=async()=>{const id=$('recordId').value;if(id&&confirm('Delete this loan?')){await api('deleteLoan',{recordId:id});$('loanDialog').close();loadAll()}};
$('loanSearch').oninput=renderLoans;$('loanStatus').onchange=renderLoans;$('refreshBtn').onclick=loadAll;
let calDate=new Date();function renderCalendar(){const y=calDate.getFullYear(),m=calDate.getMonth();$('calendarTitle').textContent=calDate.toLocaleDateString('en-US',{month:'long',year:'numeric'});const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());let html=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=>`<div class="day-name">${d}</div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10);const events=loans.filter(l=>l.nextFollowUp===iso||l.targetClosing===iso);html+=`<div class="cal-day ${d.getMonth()!==m?'muted':''}"><strong>${d.getDate()}</strong>${events.map(l=>`<div class="event">${l.targetClosing===iso?'Closing':'Follow-up'}: ${esc(l.borrowerName||l.loanNumber)}</div>`).join('')}</div>`}$('calendarGrid').innerHTML=html}$('prevMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderCalendar()};$('nextMonth').onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderCalendar()};
function renderComms(){$('emailLoan').innerHTML='<option value="">Select borrower / loan</option>'+loans.filter(l=>l.email).map(l=>`<option value="${esc(l.recordId)}">${esc(l.borrowerName)} — ${esc(l.loanNumber)}</option>`).join('');const logs=JSON.parse(localStorage.getItem('bcf_comms_v93')||'[]');$('communicationLog').innerHTML=logs.slice(0,10).map(x=>`<div class="listitem"><div><strong>${esc(x.subject)}</strong><small>${esc(x.to)} · ${esc(x.date)}</small></div></div>`).join('')||'<p>No communication logged yet.</p>'}
$('emailLoan').onchange=e=>{const l=loans.find(x=>x.recordId===e.target.value);if(l){$('emailTo').value=l.email||'';$('emailSubject').value=`BearCrest Funding — ${l.loanNumber||'Loan Update'}`}};window.composeFor=id=>{setView('communications');$('emailLoan').value=id;$('emailLoan').dispatchEvent(new Event('change'))};$('saveDraftBtn').onclick=()=>{localStorage.setItem('bcf_draft_v93',JSON.stringify({to:$('emailTo').value,subject:$('emailSubject').value,body:$('emailBody').value}));alert('Draft saved on this device.')};$('sendEmailBtn').onclick=()=>{const to=$('emailTo').value,subject=$('emailSubject').value,body=$('emailBody').value;if(!to)return alert('Enter an email address.');const logs=JSON.parse(localStorage.getItem('bcf_comms_v93')||'[]');logs.unshift({to,subject,date:new Date().toLocaleString()});localStorage.setItem('bcf_comms_v93',JSON.stringify(logs));location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;renderComms()};
$('webAppUrl').value=config.webAppUrl||'';$('saveSettingsBtn').onclick=()=>{config.webAppUrl=$('webAppUrl').value.trim();localStorage.setItem(CFG,JSON.stringify(config));$('connectionResult').textContent='Connection saved.';loadAll()};$('testConnectionBtn').onclick=async()=>{try{const url=$('webAppUrl').value.trim();const old=config.webAppUrl;config.webAppUrl=url;await api('getAll');$('connectionResult').textContent='Connected successfully.';config.webAppUrl=old}catch(e){$('connectionResult').textContent=e.message}};
const draft=JSON.parse(localStorage.getItem('bcf_draft_v93')||'null');if(draft){$('emailTo').value=draft.to||'';$('emailSubject').value=draft.subject||'';$('emailBody').value=draft.body||''}const h=new Date().getHours();$('dashboardGreeting').textContent=`${h<12?'Good morning':h<17?'Good afternoon':'Good evening'}, Joel.`;if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=931');renderAll();renderCalendar();if(config.webAppUrl)loadAll();


// Familiar loan-form quick actions. These use the values already entered in the form.
function cleanPhone(v){return String(v||'').replace(/[^0-9+]/g,'')}
$('backToLoans').onclick=e=>{e.preventDefault();$('loanDialog').close();setView('loans')};
$('callBorrower').onclick=()=>{const p=cleanPhone($('phone').value);if(!p)return alert('Enter a phone number first.');location.href='tel:'+p};
$('textBorrower').onclick=()=>{const p=cleanPhone($('phone').value);if(!p)return alert('Enter a phone number first.');location.href='sms:'+p};
$('emailBorrower').onclick=()=>{const to=$('email').value.trim();if(!to)return alert('Enter an email address first.');$('loanDialog').close();setView('communications');$('emailTo').value=to;$('emailSubject').value='BearCrest Funding — '+($('loanNumber').value||'Loan Update')};
$('directionsBorrower').onclick=()=>{const a=$('propertyAddress').value.trim();if(!a)return alert('Enter a property address first.');window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(a),'_blank','noopener')};
