(function(){
const APP_VERSION=window.BEARCREST_CONFIG?.appVersion||"11.0",APP_EDITION=window.BEARCREST_CONFIG?.edition||"Multi-User Edition";
const SUB_KEY="bearcrest_lender_submissions_v11",AUDIT_KEY="bearcrest_audit_v11",MASTER_KEY=typeof STORAGE_KEY!=="undefined"?STORAGE_KEY:"bearcrest_loans_v4_1_clean";
const getUser=()=>window.BearCrestAuth?.getCurrentUser?.();
const isAdmin=()=>window.BearCrestAuth?.isAdmin?.();
const readMaster=()=>{try{return JSON.parse(localStorage.getItem(MASTER_KEY)||"[]");}catch{return [];}};
const readSubs=()=>{try{return JSON.parse(localStorage.getItem(SUB_KEY)||"[]");}catch{return [];}};
const writeSubs=x=>localStorage.setItem(SUB_KEY,JSON.stringify(x));
function audit(action,loanId="",details=""){const u=getUser();let a=[];try{a=JSON.parse(localStorage.getItem(AUDIT_KEY)||"[]");}catch{}a.unshift({id:uuid(),at:new Date().toISOString(),userId:u?.id||"",user:u?.fullName||"Unknown",action,loanId,details});localStorage.setItem(AUDIT_KEY,JSON.stringify(a.slice(0,1000)));}
function canView(l){const u=getUser();return !u||u.role==="Administrator"||l.assignedTo===u.id||l.assignedTo===u.fullName;}
function applyRole(){
 const u=getUser();if(!u)return;
 document.querySelectorAll(".admin-only").forEach(el=>el.classList.toggle("hidden",u.role!=="Administrator"));
 const footer=document.getElementById("v5FooterStats");if(footer)footer.textContent=`BearCrest CRM · Version ${APP_VERSION} – ${APP_EDITION} · ${u.fullName} (${u.role})`;
 if(u.role!=="Administrator"){
   const master=readMaster();window.__bcfMasterLoans=master;loans=master.filter(canView).map(normalizeLoan);
   const originalSave=window.__bcfOriginalSave||save;window.__bcfOriginalSave=originalSave;
   save=function(){const currentIds=new Set(loans.map(x=>x.loanId));const hidden=(window.__bcfMasterLoans||readMaster()).filter(x=>!currentIds.has(x.loanId)&&!canView(x));localStorage.setItem(MASTER_KEY,JSON.stringify([...loans,...hidden]));render();};
   document.getElementById("sidebarSettingsBtn")?.classList.add("hidden");
 }
 populateAssignees();render();renderUsers();renderSubmissionCenter();audit("Signed in");
}
function populateAssignees(){const sel=document.getElementById("assignedTo");if(!sel)return;const current=sel.value;sel.innerHTML='<option value="">Unassigned</option>'+BearCrestAuth.getUsers().filter(u=>u.active).map(u=>`<option value="${esc(u.id)}">${esc(u.fullName)} — ${esc(u.role)}</option>`).join("");sel.value=current;}
function renderUsers(){const box=document.getElementById("userManagementList");if(!box||!isAdmin())return;const users=BearCrestAuth.getUsers();box.innerHTML=users.map(u=>`<div class="v11-row"><div><strong>${esc(u.fullName)}</strong><small>@${esc(u.username)} · ${esc(u.role)}</small></div><span class="status-pill">${u.active?"Active":"Disabled"}</span><button onclick="BCFV11.editUser('${u.id}')">Edit</button></div>`).join("");}
function openUser(user){if(!isAdmin())return alert("Administrator access is required.");document.getElementById("userId").value=user?.id||"";document.getElementById("userFullName").value=user?.fullName||"";document.getElementById("userUsername").value=user?.username||"";document.getElementById("userRole").value=user?.role||"Loan Officer";document.getElementById("userActive").value=String(user?.active!==false);document.getElementById("userPassword").value="";document.getElementById("userMustChange").checked=user?.mustChange!==false;document.getElementById("deleteUserBtn").classList.toggle("hidden",!user||user.id==="admin");document.getElementById("userDialogTitle").textContent=user?"Edit User":"Add User";document.getElementById("userDialog").showModal();}
function saveUser(e){e.preventDefault();let users=BearCrestAuth.getUsers();const id=document.getElementById("userId").value||uuid(),existing=users.find(u=>u.id===id),username=document.getElementById("userUsername").value.trim(),password=document.getElementById("userPassword").value;if(users.some(u=>u.id!==id&&u.username.toLowerCase()===username.toLowerCase()))return alert("That username is already being used.");if(!existing&&!validPassword(password))return alert("Use a temporary password containing at least 10 characters.");const data={id,fullName:document.getElementById("userFullName").value.trim(),username,role:document.getElementById("userRole").value,active:document.getElementById("userActive").value==="true",mustChange:document.getElementById("userMustChange").checked,password:password||existing?.password,createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(existing)Object.assign(existing,data);else users.push(data);BearCrestAuth.saveUsers(users);document.getElementById("userDialog").close();populateAssignees();renderUsers();audit(existing?"Updated user":"Created user","",data.fullName);}
function deleteUser(){const id=document.getElementById("userId").value;if(!id||id==="admin")return;if(!confirm("Delete this user account? Their assigned loans will remain in the CRM."))return;BearCrestAuth.saveUsers(BearCrestAuth.getUsers().filter(u=>u.id!==id));document.getElementById("userDialog").close();populateAssignees();renderUsers();audit("Deleted user","",id);}
function loanForSubmission(){return loans.find(l=>l.loanId===document.getElementById("submissionLoanId").value);}
function submissionHtml(loan,sub={}){const pct=(a,b)=>b?`${Math.round(Number(a||0)/Number(b)*100)}%`:"—";return `<div class="submission-sheet"><div class="submission-head"><img src="bcf-logo.png"><div><h2>BearCrest Funding, LLC</h2><b>Lender Submission Summary</b></div><div>${esc(loan.loanNumber||"")}<br>${new Date().toLocaleDateString()}</div></div><div class="submission-grid">${[["Borrower",loan.borrowerName],["Entity",loan.entityName],["Property",loan.propertyAddress],["Program",loan.program],["Property Type",loan.propertyType],["Loan Request",money(loan.loanAmount)||"—"],["Purchase Price",money(loan.purchasePrice)||"—"],["Rehab Budget",money(loan.rehabBudget)||"—"],["As-Is Value",money(loan.asIsValue)||"—"],["ARV",money(loan.arv)||"—"],["LTC",pct(loan.loanAmount,Number(loan.purchasePrice||0)+Number(loan.rehabBudget||0))],["LTARV",pct(loan.loanAmount,loan.arv)],["FICO",loan.fico||"—"],["Experience",loan.experience?`${loan.experience} completed project(s)`:"—"],["Liquidity",money(loan.liquidity)||"—"],["Exit Strategy",loan.exitStrategy||"—"],["Target Closing",loan.targetClosing||"—"],["Requested Lender",sub.lender||loan.lender||"—"]].map(([k,v])=>`<div><small>${k}</small><strong>${esc(v)}</strong></div>`).join("")}</div><div class="submission-notes"><h3>Deal Summary & Lender Notes</h3><p>${esc(sub.notes||loan.lenderNotes||"No lender notes entered.").replace(/\n/g,"<br>")}</p></div></div>`;}
function openSubmission(loanId){const loan=loans.find(l=>l.loanId===loanId||l.loanId===document.getElementById("loanId")?.value);if(!loan)return alert("Open or save a loan first.");document.getElementById("submissionLoanId").value=loan.loanId;const lenderSel=document.getElementById("submissionLender"),names=(typeof lenders!=="undefined"?lenders:[]).map(x=>x.name).filter(Boolean);lenderSel.innerHTML='<option value="">Select lender...</option>'+names.map(n=>`<option>${esc(n)}</option>`).join("");lenderSel.value=loan.lender||"";document.getElementById("submissionDate").value=today();document.getElementById("submissionFollowUp").value="";document.getElementById("submissionContact").value="";document.getElementById("submissionNotes").value=loan.lenderNotes||"";document.getElementById("submissionResponse").value="";document.getElementById("submissionStatus").value="Preparing";refreshPreview();document.getElementById("lenderSubmissionDialog").showModal();}
function refreshPreview(){const loan=loanForSubmission();if(!loan)return;document.getElementById("submissionPreview").innerHTML=submissionHtml(loan,{lender:document.getElementById("submissionLender").value,notes:document.getElementById("submissionNotes").value});}
function saveSubmission(e){e.preventDefault();const loan=loanForSubmission();if(!loan)return;const sub={id:uuid(),loanId:loan.loanId,lender:document.getElementById("submissionLender").value,status:document.getElementById("submissionStatus").value,dateSubmitted:document.getElementById("submissionDate").value,followUp:document.getElementById("submissionFollowUp").value,contact:document.getElementById("submissionContact").value.trim(),notes:document.getElementById("submissionNotes").value.trim(),response:document.getElementById("submissionResponse").value.trim(),createdBy:getUser()?.fullName||"",createdAt:new Date().toISOString()};const subs=readSubs();subs.unshift(sub);writeSubs(subs);loan.lenderNotes=sub.notes;if(sub.lender)loan.lender=sub.lender;if(sub.status==="Submitted"){loan.status="Submitted";loan.dateSubmitted=sub.dateSubmitted||today();}save();document.getElementById("lenderSubmissionDialog").close();renderSubmissionCenter();audit("Saved lender submission",loan.loanId,`${sub.lender} · ${sub.status}`);}
function printSubmission(){const loan=loanForSubmission();if(!loan)return;const html=submissionHtml(loan,{lender:document.getElementById("submissionLender").value,notes:document.getElementById("submissionNotes").value});const w=window.open("","_blank");w.document.write(`<html><head><title>Lender Submission - ${esc(loan.loanNumber||loan.borrowerName)}</title><style>body{font-family:Arial;margin:30px;color:#17251d}.submission-head{display:flex;align-items:center;gap:16px;border-bottom:3px solid #b59a52;padding-bottom:14px}.submission-head img{width:70px}.submission-head div:last-child{margin-left:auto;text-align:right}.submission-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:20px 0}.submission-grid div{border:1px solid #ddd;padding:10px}.submission-grid small{display:block;color:#666}.submission-notes{border:1px solid #ddd;padding:14px}@media print{button{display:none}}</style></head><body><button onclick="print()">Print / Save PDF</button>${html}</body></html>`);w.document.close();}
function renderSubmissionCenter(){const box=document.getElementById("submissionCenterList"),stats=document.getElementById("submissionStats");if(!box)return;const subs=readSubs().filter(s=>loans.some(l=>l.loanId===s.loanId));if(stats)stats.innerHTML=`<div class="stat"><strong>${subs.length}</strong><span>Total Submissions</span></div><div class="stat"><strong>${subs.filter(s=>s.status==="Reviewing").length}</strong><span>Reviewing</span></div><div class="stat"><strong>${subs.filter(s=>s.status==="Approved").length}</strong><span>Approved</span></div><div class="stat"><strong>${subs.filter(s=>s.status==="Declined").length}</strong><span>Declined</span></div>`;box.innerHTML=subs.length?subs.map(s=>{const l=loans.find(x=>x.loanId===s.loanId);return `<div class="v11-row"><div><strong>${esc(l?.borrowerName||"Loan")}</strong><small>${esc(l?.propertyAddress||"")} · ${esc(s.lender||"No lender")}</small></div><div><span class="status-pill">${esc(s.status)}</span><small>${esc(s.dateSubmitted||"")}</small></div><button onclick="BCFV11.openSubmission('${s.loanId}')">New Submission</button><button onclick="editLoan('${s.loanId}')">Open Loan</button></div>`}).join(""):'<div class="empty-state">No lender submissions have been saved yet.</div>';}
const oldEdit=window.editLoan;window.editLoan=function(id){const l=loans.find(x=>x.loanId===id);if(!l||!canView(l))return alert("You do not have access to this loan.");oldEdit(id);setTimeout(()=>{populateAssignees();document.getElementById("assignedTo").value=l.assignedTo||"";},0);};
window.BCFV11={editUser:id=>openUser(BearCrestAuth.getUsers().find(u=>u.id===id)),openSubmission};
document.addEventListener("bearcrest:user-login",applyRole);
document.addEventListener("DOMContentLoaded",()=>{
 document.getElementById("addUserBtn")?.addEventListener("click",()=>openUser());document.getElementById("userForm")?.addEventListener("submit",saveUser);document.getElementById("closeUserDialogBtn")?.addEventListener("click",()=>document.getElementById("userDialog").close());document.getElementById("cancelUserBtn")?.addEventListener("click",()=>document.getElementById("userDialog").close());document.getElementById("deleteUserBtn")?.addEventListener("click",deleteUser);
 document.getElementById("lenderSubmissionBtn")?.addEventListener("click",()=>openSubmission());document.getElementById("lenderSubmissionForm")?.addEventListener("submit",saveSubmission);document.getElementById("closeLenderSubmissionBtn")?.addEventListener("click",()=>document.getElementById("lenderSubmissionDialog").close());document.getElementById("cancelSubmissionBtn")?.addEventListener("click",()=>document.getElementById("lenderSubmissionDialog").close());document.getElementById("printSubmissionBtn")?.addEventListener("click",printSubmission);["submissionLender","submissionNotes"].forEach(id=>document.getElementById(id)?.addEventListener("input",refreshPreview));
 if(sessionValid())applyRole();
});
})();
